"""add road block

Revision ID: 00249eb74f01
Revises: 18150583beb8
Create Date: 2026-09-09 08:10:04.360503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00249eb74f01'
down_revision: Union[str, Sequence[str], None] = '18150583beb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('blocked_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['road.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadblock')
    # ### end Alembic commands ###
