"""add zone_id to recommendation

Revision ID: 18150583beb8
Revises: 95a0f270040f
Create Date: 2026-09-08 21:22:36.523453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18150583beb8'
down_revision: Union[str, Sequence[str], None] = '95a0f270040f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('zone_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recommendation', 'zone', ['zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendation', type_='foreignkey')
    op.drop_column('recommendation', 'zone_id')
    # ### end Alembic commands ###
