"""initial schema: user, zone, shelter, road, scenario, simulation_run, simulation_tick

Revision ID: 2bbc6f98b51d
Revises: 
Create Date: 2026-09-06 12:36:37.934616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2bbc6f98b51d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scenario_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('elevation_tier', sa.Enum('HIGH', 'MID', 'LOW', name='elevationtier'), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('elderly_pct', sa.Float(), nullable=False),
    sa.Column('population_density', sa.Integer(), nullable=True),
    sa.Column('elevation_m', sa.Integer(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('hospital_count', sa.Integer(), nullable=False),
    sa.Column('flood_risk_base', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_code'), 'zone', ['code'], unique=True)
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.Column('has_medical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelter_code'), 'shelter', ['code'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('CENTRAL_COORDINATOR', 'ZONE_ADMIN', 'NDRF', 'CITIZEN', name='roleenum'), nullable=False),
    sa.Column('hashed_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_table('road',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_zone_id', sa.Integer(), nullable=False),
    sa.Column('to_zone_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_zone_id'], ['zone.id'], ),
    sa.ForeignKeyConstraint(['to_zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulationrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('started_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'PAUSED', 'COMPLETED', name='simulationstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulationtick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_run_id', sa.Integer(), nullable=False),
    sa.Column('tick_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('raw_state_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulationrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulationtick')
    op.drop_table('simulationrun')
    op.drop_table('road')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_shelter_code'), table_name='shelter')
    op.drop_table('shelter')
    op.drop_index(op.f('ix_zone_code'), table_name='zone')
    op.drop_table('zone')
    op.drop_table('scenario')
    # ### end Alembic commands ###
