"""add sensor_event, citizen_report, risk_score, vulnerability_score, route_option

Revision ID: 96f989cd923e
Revises: 2bbc6f98b51d
Create Date: 2026-09-06 13:05:32.217235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96f989cd923e'
down_revision: Union[str, Sequence[str], None] = '2bbc6f98b51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizenreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'REVIEWED', 'RESOLVED', name='citizenreportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensorevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_run_id', sa.Integer(), nullable=True),
    sa.Column('source_adapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulationrun.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riskscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_tick_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_tick_id'], ['simulationtick.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routeoption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_tick_id', sa.Integer(), nullable=False),
    sa.Column('from_zone_id', sa.Integer(), nullable=False),
    sa.Column('to_shelter_id', sa.Integer(), nullable=False),
    sa.Column('path_json', sa.JSON(), nullable=False),
    sa.Column('eta', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('USABLE', 'DEGRADED', 'BLOCKED', name='routestatus'), nullable=False),
    sa.ForeignKeyConstraint(['from_zone_id'], ['zone.id'], ),
    sa.ForeignKeyConstraint(['simulation_tick_id'], ['simulationtick.id'], ),
    sa.ForeignKeyConstraint(['to_shelter_id'], ['shelter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerabilityscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_tick_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_tick_id'], ['simulationtick.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerabilityscore')
    op.drop_table('routeoption')
    op.drop_table('riskscore')
    op.drop_table('sensorevent')
    op.drop_table('citizenreport')
    # ### end Alembic commands ###
